-- TERCERA FORMA PARA CREAR UN CONSTRAINT --> PRIMARY KEY
CREATE TABLE ALUMNOS(
    ID_MATRICULA NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    SEXO NVARCHAR2(100),
    CONSTRAINT PK_ALUMNOS PRIMARY KEY (ID_MATRICULA)
);

--insertar datos a la tabla
INSERT INTO ALUMNOS VALUES(1001, 'LEONARDO', 'LOPEZ', 25, 'MASCULINO');
INSERT INTO ALUMNOS VALUES(1002, 'SANTIAGO', 'GONZALES', 23, 'MASCULINO');
INSERT INTO ALUMNOS VALUES(1003, 'JOSE', 'HERNANDEZ',24, 'MASCULINO');
INSERT INTO ALUMNOS VALUES(1004, 'LUIS', 'PACHECO', 25, 'MASCULINO');
INSERT INTO ALUMNOS VALUES(1005, 'LAURA', 'HERNANDEZ',23, 'FEMENINO');
INSERT INTO ALUMNOS VALUES(1006, 'SAMANTA', 'GUTIERREZ',24, 'FEMENINO');

--MOSTRAR DATOS
SELECT * FROM ALUMNOS;

--CONFIRMAR CAMBIOS DE LA BASE DE DATOS
COMMIT;

--ELIMINAR TABLA COMPLETA
DROP TABLE ALUMNOS; 
-- ELIMINAR TODOS LOS REGISTROS DE LATABLE
DELETE FROM ALUMNOS;

--REVERTIR LOS CAMBIOS REALIZADOS
ROLLBACK;

--ACTUALIZAR DATOS DE UNA COLUMNA
UPDATE ALUMNOS SET UNIVERSIDAD = 'UNIVERSIDAD DE GUADALAJARA' WHERE ID_MATRICULA = 1001;
UPDATE ALUMNOS SET UNIVERSIDAD = 'INSTITUTO TECNOLOGICO DE MEXICO CAMPUS TZOMPANTEPEC' WHERE ID_MATRICULA = 1002;
UPDATE ALUMNOS SET UNIVERSIDAD = 'UNIVERSIDAD DEL VALLE DE TLAXCALA' WHERE ID_MATRICULA = 1003;
UPDATE ALUMNOS SET UNIVERSIDAD = 'UNIVERSIDAD TECNOLOGICA DE TLAXCALA' WHERE ID_MATRICULA = 1004;


-- MODIFICAR ESTRUCTURA DE LA TABLA AGREGANDO UN NUEVO CAMPO
ALTER TABLE ALUMNOS ADD UNIVERSIDAD NVARCHAR2(100);
--AGREGAR CAMPO DE TIPO NVARCHAR2 CON UN TAMAÑO DE 50 CARACTERES PARA ESPECIFICAR EL DOMICILIO DE UNIVERSIDAD

--MOSTRAR DATOS DE ALGUNA COLUMNA EN ESPECIFICO
SELECT ID_MATRICULA, NOMBRE, EDAD, UNIVERSIDAD FROM ALUMNOS;

--CAMBIAR NOMBRE DE COLUMNA
ALTER TABLE ALUMNOS RENAME COLUMN APP TO APELLIDO;

--ACTUALIZAR DATOS DE UNA COLUMNA
UPDATE ALUMNOS SET APELLIDO = 'GARCIA' WHERE ID_MATRICULA = 1005;

--ORDENAMIENTO DE REGISTROS DE ACUERDO A UN CAMPO DESCENDENTE
SELECT * FROM ALUMNOS ORDER BY NOMBRE DESC;
-- ORDENAR DE MANERA ASCENDENTE
SELECT * FROM ALUMNOS ORDER BY NOMBRE ASC;


--BUSQUEDA DE DATOS DE UNA COLUMNA QUE COMIENZEN POR UNA LETRA
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE 'Z%'
--BUSQUEDA DE DATOS DE UNA COLUMNA QUE TERMINEN POR UNA LETRA O NUMERO
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE '%Z'
--BUSQUEDA DE DATOS DE UNA COLUMNA QUE CONTENGA POR UNA LETRA O NUMERO
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE '%Z%'

--BUSCAR ALUMNOS QUE SU UNIVERSIDAD SEA NULA
SELECT * FROM ALUMNOS WHERE UNIVERSIDAD IS NULL;
--BUSCAR ALUMNOS QUE SU UNIVERSIDAD NO SEA NULA
SELECT * FROM ALUMNOS WHERE UNIVERSIDAD IS NOT NULL;

--BUSCAR ALUMNOS QUE SU EDAD SEA MENOR A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD < 24;
--BUSCAR ALUMNOS QUE SU EDAD SEA MAYOR A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD > 24;
--BUSCAR ALUMNOS QUE SU EDAD SEA ENTRE A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD > 24 AND EDAD < 26;
-- UTILIZANDO FFUNCION BETWEEN
SELECT * FROM ALUMNOS WHERE EDAD BETWEEN 23 AND 24; 


--BUSCAR DATOS DONDE EL ID SEA ESPECIFICADO
SELECT * FROM ALUMNOS WHERE ID_MATRICULA = 1002 OR ID_MATRICULA = 1003 OR ID_MATRICULA = 1006;
--FORMA REDUCIDA
SELECT * FROM ALUMNOS WHERE ID_MATRICULA IN (1002,1003,1006);


--AGRUPAR DATOS DEPENDIENDO CIERTO VALOR
SELECT COUNT FROM ALUMNOS GROUP BY SEXO;

--funcion DISTINCT MUESTRA LOS VALORES DISTINTOS Y NUMERO QUE TIENE DE DICHO VALOR
SELECT DISTINCT EDAD FROM ALUMNOS;
SELECT DISTINCT APELLIDO FROM ALUMNOS;
SELECT DISTINCT SEXO FROM ALUMNOS;

--CONTAR CUANTOS REGISTROS TENGO EN LA TABLA... EL 'AS' ASIGNA UN ALIAS A LA BUSQUEDA EN LUGAR DE MOSTRAR EL NOMBRE DE LA COLUMNA 
SELECT COUNT (ID_MATRICULA) AS TOTAL_ALUMNOS FROM ALUMNOS;