-- TERCERA FORMA PARA CREAR UN CONSTRAINT --> PRIMARY KEY
CREATE TABLE ALUMNOS(
    ID_MATRICULA NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    SEXO NVARCHAR2(100),
    UNIVERSIDAD NVARCHAR2(50);
    CONSTRAINT PK_ALUMNOS PRIMARY KEY (ID_MATRICULA)
);





--insertar datos a la tabla
INSERT INTO ALUMNOS VALUES(1001, 'LEONARDO', 'LOPEZ', 25, 'MASCULINO','UNIVERSIDAD DE GUADALAJARA');
INSERT INTO ALUMNOS VALUES(1002, 'SANTIAGO', 'GONZALES', 23, 'MASCULINO','INSTITUTO TECNOLOGICO DE MEXICO CAMPUS TZOMPANTEPEC');
INSERT INTO ALUMNOS VALUES(1003, 'JOSE', 'HERNANDEZ',24, 'MASCULINO','UNIVERSIDAD DEL VALLE DE TLAXCALA');
INSERT INTO ALUMNOS VALUES(1004, 'LUIS', 'PACHECO', 25, 'MASCULINO','UNIVERSIDAD DEL VALLE DE MEXICO');
INSERT INTO ALUMNOS VALUES(1005, 'LAURA', 'HERNANDEZ',23, 'FEMENINO','UNIVERSIDAD POLITECNICA DE TLAXCALA');
INSERT INTO ALUMNOS VALUES(1006, 'SAMANTA', 'GUTIERREZ',24, 'FEMENINO','UNIVERSIDAD DEL VALLE DE TLAXCALA');
INSERT INTO ALUMNOS VALUES(1007, 'JULIO CESAR', 'LUNA',25, 'MASCULINO','UNIVERSIDAD DEL ALTIPLANO DE TLAXCALA');
INSERT INTO ALUMNOS VALUES(1008,'KAREN','GARCIA', 23, 'FEMENINO', 'UNIVERSIDAD DEL VALLE MEXICO');
INSERT INTO ALUMNOS VALUES(1009,'SANTIAGO','GARCIA', 24, 'MASCULINO', 'UNIVERSIDAD POLITECNICA DE TLAXCALA');
INSERT INTO ALUMNOS VALUES(1010,'LUDWIG', 'ROMANOV',29,'MASCULINO','INSTITUTO TECNOLOGICO NACIONAL DE MEXICO CAMPUS TLAXCALA');
INSERT INTO ALUMNOS VALUES(1011,'LUIS','SANCHEZ', 20, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1012,'JORGE','SANCHEZ', 30, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1013,'LUCIO','SANCHEZ', 29, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1014,'DAMIAN','ROJAS', 25, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1015,'VENANCIO','HERNANDEZ', 20, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1016,'GERMAN','SANCHEZ', 20, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1017,'ALBERTO','HURTADO', 25, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1018,'KARLA','RODRIGUEZ', 28, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1019,'KAROL','ZAMORA', 29, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1020,'KAROLINA','FERNANDEZ', 20, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1021,'KENIA','LUNA', 20, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1022,'KARINA','MARTINEZ', 25, 'MASCULINO', 'UNIVERSIDAD DE LA SALLE PUEBLA');
INSERT INTO ALUMNOS VALUES(1023,'ANA','LOPEZ',21,'FEMENINO','TECNM','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1024,'CARLOS','RAMIREZ',23,'MASCULINO','BUAP','PUEBLA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1025,'MARIA','HERNANDEZ',20,'FEMENINO','UNAM','TLAXCALA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1026,'JOSE','MARTINEZ',25,'MASCULINO','IPN','CIUDAD DE MEXICO, CDMX');
INSERT INTO ALUMNOS VALUES(1027,'LAURA','GARCIA',22,'FEMENINO','UATX','CHIAUTEMPAN, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1028,'MIGUEL','TORRES',24,'MASCULINO','TECNM','HUAMANTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1029,'SOFIA','FLORES',19,'FEMENINO','BUAP','CHOLULA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1030,'DANIEL','SANCHEZ',26,'MASCULINO','UNAM','COYOACAN, CDMX');
INSERT INTO ALUMNOS VALUES(1031,'FERNANDA','ROJAS',21,'FEMENINO','IPN','GUSTAVO A. MADERO, CDMX');
INSERT INTO ALUMNOS VALUES(1032,'LUIS','MORALES',28,'MASCULINO','UATX','APIZACO, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1033,'PAOLA','CRUZ',23,'FEMENINO','TECNM','YAUHQUEMEHCAN, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1034,'JORGE','ORTIZ',27,'MASCULINO','BUAP','PUEBLA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1035,'DIANA','CASTILLO',20,'FEMENINO','UNAM','TLALPAN, CDMX');
INSERT INTO ALUMNOS VALUES(1036,'RICARDO','MENDOZA',29,'MASCULINO','IPN','AZCAPOTZALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1037,'ALEJANDRA','VARGAS',22,'FEMENINO','UATX','TLAXCALA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1038,'PEDRO','ROMERO',24,'MASCULINO','TECNM','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1039,'VALERIA','GUZMAN',19,'FEMENINO','BUAP','ATLIXCO, PUEBLA');
INSERT INTO ALUMNOS VALUES(1040,'OSCAR','REYES',31,'MASCULINO','UNAM','XOCHIMILCO, CDMX');
INSERT INTO ALUMNOS VALUES(1041,'ANDREA','MOLINA',25,'FEMENINO','IPN','IZTACALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1042,'RAUL','AGUILAR',27,'MASCULINO','UATX','HUAMANTLA, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1043,'MONICA','SALAZAR',22,'FEMENINO','TECNM','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1044,'ALBERTO','NAVARRO',30,'MASCULINO','BUAP','TEHUACAN, PUEBLA');
INSERT INTO ALUMNOS VALUES(1045,'KAREN','MEDINA',21,'FEMENINO','UNAM','BENITO JUAREZ, CDMX');
INSERT INTO ALUMNOS VALUES(1046,'SERGIO','DELGADO',26,'MASCULINO','IPN','MIGUEL HIDALGO, CDMX');
INSERT INTO ALUMNOS VALUES(1047,'NATALIA','CORTES',20,'FEMENINO','UATX','CALPULALPAN, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1048,'HECTOR','VEGA',32,'MASCULINO','TECNM','TLAXCO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1049,'GABRIELA','CAMPOS',23,'FEMENINO','BUAP','SAN MARTIN TEXMELUCAN, PUEBLA');
INSERT INTO ALUMNOS VALUES(1050,'IVAN','SOTO',24,'MASCULINO','UNAM','CUAUHTEMOC, CDMX');
INSERT INTO ALUMNOS VALUES(1051,'CLAUDIA','LUNA',28,'FEMENINO','IPN','VENUSTIANO CARRANZA, CDMX');
INSERT INTO ALUMNOS VALUES(1052,'MARIO','RIVERA',29,'MASCULINO','UATX','CHIAUTEMPAN, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1053,'PATRICIA','SILVA',25,'FEMENINO','TECNM','HUAMANTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1054,'EDUARDO','MONTES',33,'MASCULINO','BUAP','PUEBLA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1055,'LUCIA','MIRANDA',19,'FEMENINO','UNAM','COYOACAN, CDMX');
INSERT INTO ALUMNOS VALUES(1056,'ROBERTO','CABRERA',27,'MASCULINO','IPN','IZTAPALAPA, CDMX');
INSERT INTO ALUMNOS VALUES(1057,'XIMENA','MORA',22,'FEMENINO','UATX','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1058,'ARTURO','VALDEZ',30,'MASCULINO','TECNM','ZACATELCO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1059,'ELENA','PEREZ',24,'FEMENINO','BUAP','CHOLULA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1060,'FRANCISCO','JUAREZ',35,'MASCULINO','UNAM','TLALPAN, CDMX');
INSERT INTO ALUMNOS VALUES(1061,'BEATRIZ','NAVA',26,'FEMENINO','IPN','AZCAPOTZALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1062,'MANUEL','ESCOBAR',31,'MASCULINO','UATX','TLAXCALA, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1063,'ADRIANA','MALDONADO',23,'FEMENINO','TECNM','CONTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1064,'JAVIER','MEJIA',28,'MASCULINO','BUAP','ATLIXCO, PUEBLA');
INSERT INTO ALUMNOS VALUES(1065,'LILIANA','PADILLA',21,'FEMENINO','UNAM','XOCHIMILCO, CDMX');
INSERT INTO ALUMNOS VALUES(1066,'ALEJANDRO','MIRANDA',34,'MASCULINO','IPN','GUSTAVO A. MADERO, CDMX');
INSERT INTO ALUMNOS VALUES(1067,'VERONICA','ZAMORA',29,'FEMENINO','UATX','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1068,'DIEGO','ACOSTA',20,'MASCULINO','TECNM','HUAMANTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1069,'CAMILA','MUNOZ',18,'FEMENINO','BUAP','TEHUACAN, PUEBLA');
INSERT INTO ALUMNOS VALUES(1070,'EMILIO','PACHECO',25,'MASCULINO','UNAM','BENITO JUAREZ, CDMX');
INSERT INTO ALUMNOS VALUES(1071,'REGINA','SOLIS',22,'FEMENINO','IPN','IZTACALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1072,'MARCO','TAPIA',27,'MASCULINO','UATX','CHIAUTEMPAN, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1073,'DANIELA','CARRILLO',24,'FEMENINO','TECNM','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1074,'VICTOR','DOMINGUEZ',36,'MASCULINO','BUAP','SAN MARTIN TEXMELUCAN, PUEBLA');
INSERT INTO ALUMNOS VALUES(1075,'MARIANA','FUENTES',20,'FEMENINO','UNAM','MIGUEL HIDALGO, CDMX');
INSERT INTO ALUMNOS VALUES(1076,'GERARDO','IBARRA',32,'MASCULINO','IPN','CUAUHTEMOC, CDMX');
INSERT INTO ALUMNOS VALUES(1077,'RENATA','LARA',21,'FEMENINO','UATX','YAUHQUEMEHCAN, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1078,'ARMANDO','LEON',29,'MASCULINO','TECNM','TLAXCO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1079,'ISABEL','MARQUEZ',23,'FEMENINO','BUAP','PUEBLA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1080,'MAURICIO','NUNEZ',26,'MASCULINO','UNAM','VENUSTIANO CARRANZA, CDMX');
INSERT INTO ALUMNOS VALUES(1081,'CAROLINA','OCHOA',28,'FEMENINO','IPN','IZTAPALAPA, CDMX');
INSERT INTO ALUMNOS VALUES(1082,'RAMON','PALACIOS',37,'MASCULINO','UATX','CALPULALPAN, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1083,'SANDRA','QUINTERO',30,'FEMENINO','TECNM','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1084,'GUSTAVO','ROSAS',33,'MASCULINO','BUAP','CHOLULA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1085,'LORENA','SERRANO',25,'FEMENINO','UNAM','COYOACAN, CDMX');
INSERT INTO ALUMNOS VALUES(1086,'ENRIQUE','TREVINO',31,'MASCULINO','IPN','TLALPAN, CDMX');
INSERT INTO ALUMNOS VALUES(1087,'MELISSA','URIBE',22,'FEMENINO','UATX','ZACATELCO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1088,'ALFREDO','VILLARREAL',34,'MASCULINO','TECNM','HUAMANTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1089,'PAULINA','ZEPEDA',19,'FEMENINO','BUAP','ATLIXCO, PUEBLA');
INSERT INTO ALUMNOS VALUES(1090,'RODRIGO','ARELLANO',27,'MASCULINO','UNAM','AZCAPOTZALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1091,'MAYRA','BENITEZ',24,'FEMENINO','IPN','GUSTAVO A. MADERO, CDMX');
INSERT INTO ALUMNOS VALUES(1092,'CESAR','CONTRERAS',38,'MASCULINO','UATX','TLAXCALA, TLAXCALA');

INSERT INTO ALUMNOS VALUES(1093,'ERIKA','DIAZ',26,'FEMENINO','TECNM','CHIAUTEMPAN, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1094,'HUGO','ESPINOZA',30,'MASCULINO','BUAP','TEHUACAN, PUEBLA');
INSERT INTO ALUMNOS VALUES(1095,'IRMA','FRANCO',32,'FEMENINO','UNAM','XOCHIMILCO, CDMX');
INSERT INTO ALUMNOS VALUES(1096,'LEONARDO','GALLARDO',23,'MASCULINO','IPN','BENITO JUAREZ, CDMX');
INSERT INTO ALUMNOS VALUES(1097,'MIRNA','HIDALGO',27,'FEMENINO','UATX','APIZACO, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1098,'NOE','JIMENEZ',35,'MASCULINO','TECNM','CONTLA, TLAXCALA');
INSERT INTO ALUMNOS VALUES(1099,'OLIVIA','LOZANO',29,'FEMENINO','BUAP','PUEBLA, PUEBLA');
INSERT INTO ALUMNOS VALUES(1100,'PABLO','MENA',22,'MASCULINO','UNAM','IZTACALCO, CDMX');
INSERT INTO ALUMNOS VALUES(1101,'ROCIO','NEGRETE',31,'FEMENINO','IPN','MIGUEL HIDALGO, CDMX');
INSERT INTO ALUMNOS VALUES(1102,'TOMAS','OLVERA',40,'MASCULINO','UATX','HUAMANTLA, TLAXCALA');
-------
COMMIT;

--MOSTRAR DATOS
SELECT * FROM ALUMNOS;

--CONFIRMAR CAMBIOS DE LA BASE DE DATOS
COMMIT;

--ELIMINAR TABLA COMPLETA
DROP TABLE ALUMNOS;

-- ELIMINAR TODOS LOS REGISTROS DE LA TABLE
DELETE FROM ALUMNOS;

--REVERTIR LOS CAMBIOS REALIZADOS
SAVEPOINT PUNTOVERSION1;
SAVEPOINT PUNTOVERSION2;
---ROLLBACK 
ROLLBACK SAVEPOINT VERSION1;

-- MODIFICAR ESTRUCTURA DE LA TABLA AGREGANDO UN NUEVO CAMPO
ALTER TABLE ALUMNOS ADD UNIVERSIDAD NVARCHAR2(100);
ALTER TABLE ALUMNOS ADD DOMICILIO NVARCHAR2(50);
--AGREGAR CAMPO DE TIPO NVARCHAR2 CON UN TAMAÑO DE 50 CARACTERES PARA ESPECIFICAR EL DOMICILIO DE UNIVERSIDAD

--MOSTRAR DATOS DE ALGUNA COLUMNA EN ESPECIFICO
SELECT ID_MATRICULA, NOMBRE, EDAD, UNIVERSIDAD FROM ALUMNOS

--CAMBIAR NOMBRE DE COLUMNA
ALTER TABLE ALUMNOS RENAME COLUMN APP TO APELLIDO;

--ACTUALIZAR DATOS DE UNA COLUMNA
UPDATE ALUMNOS SET APELLIDO = 'GARCIA' WHERE ID_MATRICULA = 1005;

--ORDENAMIENTO DE REGISTROS DE ACUERDO A UN CAMPO DESCENDENTE
SELECT * FROM ALUMNOS ORDER BY NOMBRE DESC;
-- ORDENAR DE MANERA ASCENDENTE
SELECT * FROM ALUMNOS ORDER BY NOMBRE ASC;


--BUSQUEDA DE DATOS DE UNA COLUMNA QUE COMIENZEN POR UNA LETRA
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE 'Z%'
--BUSQUEDA DE DATOS DE UNA COLUMNA QUE TERMINEN POR UNA LETRA O NUMERO
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE '%Z'
--BUSQUEDA DE DATOS DE UNA COLUMNA QUE CONTENGA POR UNA LETRA O NUMERO
SELECT * FROM ALUMNOS WHERE APELLIDO LIKE '%Z%'

--BUSCAR ALUMNOS QUE SU UNIVERSIDAD SEA NULA
SELECT * FROM ALUMNOS WHERE UNIVERSIDAD IS NULL;
--BUSCAR ALUMNOS QUE SU UNIVERSIDAD NO SEA NULA
SELECT * FROM ALUMNOS WHERE UNIVERSIDAD IS NOT NULL;

--BUSCAR ALUMNOS QUE SU EDAD SEA MENOR A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD < 24;
--BUSCAR ALUMNOS QUE SU EDAD SEA MAYOR A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD > 24;
--BUSCAR ALUMNOS QUE SU EDAD SEA ENTRE A CIERTO NUMERO
SELECT * FROM ALUMNOS WHERE EDAD > 24 AND EDAD < 26;
-- UTILIZANDO FFUNCION BETWEEN
SELECT * FROM ALUMNOS WHERE EDAD BETWEEN 23 AND 24; 


--BUSCAR DATOS DONDE EL ID SEA ESPECIFICADO
SELECT * FROM ALUMNOS WHERE ID_MATRICULA = 1002 OR ID_MATRICULA = 1003 OR ID_MATRICULA = 1006;
--FORMA REDUCIDA
SELECT * FROM ALUMNOS WHERE ID_MATRICULA IN (1002,1003,1006);


--AGRUPAR DATOS DEPENDIENDO CIERTO VALOR
SELECT COUNT FROM ALUMNOS GROUP BY SEXO;

--funcion DISTINCT MUESTRA LOS VALORES DISTINTOS Y NUMERO QUE TIENE DE DICHO VALOR
SELECT DISTINCT EDAD FROM ALUMNOS;
SELECT DISTINCT APELLIDO FROM ALUMNOS;
SELECT DISTINCT SEXO FROM ALUMNOS;

--CONTAR CUANTOS REGISTROS TENGO EN LA TABLA... EL 'AS' ASIGNA UN ALIAS A LA BUSQUEDA EN LUGAR DE MOSTRAR EL NOMBRE DE LA COLUMNA 
SELECT COUNT (ID_MATRICULA) AS TOTAL_ALUMNOS FROM ALUMNOS;